version: "3.9"

services:
  backend:
    build: ./backend
    container_name: hypesoft-backend
    command: sh -c "npm install && npm run start:dev"
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - ./backend:/app
      - /app/node_modules

  db:
    image: mysql:8
    container_name: hypesoft-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_hypesoft
      MYSQL_USER: hype
      MYSQL_PASSWORD: hype123
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
